version: '3.4'

services:
  node-log:
    image: node-log
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
      - 9229:9229
    command: /bin/sh -c "while sleep 1000; do :; done"
    #command: "npm run dev"

networks:
  default:
    # Use a custom driver
    driver: bridge