version: '3.4'

services:
  email-node:
    image: email-node
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
